### ISSUE TITLE
Archiving doesn't seem to work at all

### ISSUE THREAD

**Issue by p-himik** [ArchiveBox/archivebox-browser-extension#32] opened 2024-11-30 08:56 UTC
I followed all the instructions, set the mode to Blocklist so everything I request is archived, and yet pressing on the "Archive Current Page" item in the context menu doesn't do anything. Not only there's no any indication that something is going on, the page doesn't show up in Archivebox, and there are no request logs on the server side.

I tried debugging the extension and it seems that there are two things happening:
1. The call to `chrome.permissions.request` never executes the callback
2. The same call executes the callback, but there's an error: `"This function must be called during a user gesture"`

Apparently, (2) could be due to the debugger. No clue about (1) though.

**Comment by pirate** [comment] 2024-12-01 01:21
Duplicate of #25

Fix is in-progress already in this PR

**Closed** 2024-12-01 01:22 UTC
